variables:
  SAFO_DEFAULT_PATH: /home/pi/safo/test_images

stages:
  - build

statistics_calculation_job:
  stage: build
  when: manual
  image: paulabeatrizolmedo/image-processor
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - cat "$RPI_IDENTITY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - mkdir $CI_PROJECT_DIR/images
    - scp $RPI_USER@$RPI_REMOTE_HOST:/$SAFO_DEFAULT_PATH/* $CI_PROJECT_DIR/images
  script:
    - python src/service/image_processor.py --path $CI_PROJECT_DIR/images/
    - mv $CI_PROJECT_DIR/images/processing_results.csv $CI_PROJECT_DIR/
  after_script:
    - rm -rf $CI_PROJECT_DIR/images
    - ls $CI_PROJECT_DIR
  artifacts:
    paths:
    - $CI_PROJECT_DIR/processing_results.csv
    expire_in: 1 hour
  tags:
    - macos
    - amd64
