variables:
  SAFO_DEFAULT_PATH: /home/pi/safo

stages:
  - build

build-job:
  stage: build
  script:
    - echo "test"
    - ls /home/pi/safo
  artifacts:
    paths:
    - $SAFO_DEFAULT_PATH/*
  tags:
    - rpi
    - local