variables:
  SAFO_DEFAULT_PATH: /home/pi/safo

stages:
  - test
  - statistics_calculation

test_connection:
  stage: test
  script:
    - eval $(ssh-agent -s)
    - cat "$RPI_IDENTITY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -v pi@192.168.100.9
  tags:
    - rpi
    - local


statistics_calculation_job:
  stage: statistics_calculation
  image: paulabeatrizolmedo/image-processor
  when: manual
  script:
    - python src/service/image_processor.py --path $CI_PROJECT_DIR/safo/test_images/
  artifacts:
    paths:
    - $CI_PROJECT_DIR/safo/test_images/processing_results.csv
  tags:
    - macos
    - amd64
