variables:
  SAFO_DEFAULT_PATH: /home/pi/safo

stages:
  - build

build-job:
  stage: build
  script:
    - echo "test"
    - ls $SAFO_DEFAULT_PATH
    - cp -r $SAFO_DEFAULT_PATH $CI_PROJECT_DIR
    - ls $CI_PROJECT_DIR
  artifacts:
    paths:
    - $CI_PROJECT_DIR/safo
  tags:
    - rpi
    - local