variables:
  SAFO_DEFAULT_PATH: /home/pi/safo/test_images

stages:
  - build

statistics_calculation_job:
  stage: build
  before_script:
    - eval $(ssh-agent -s)
    - cat "$RPI_IDENTITY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - mkdir $CI_PROJECT_DIR/images
    - scp pi@192.168.100.9:/$SAFO_DEFAULT_PATH/* $CI_PROJECT_DIR/images
  script:
    - python src/service/image_processor.py --path $CI_PROJECT_DIR/images/
  after_script:
    - rm -rf $CI_PROJECT_DIR/images
    - ls $CI_PROJECT_DIR
  tags:
    - macos
    - amd64
