FROM python:3.9.3-slim-buster

#librerías necesarias
RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install -y libgomp1 \
    && apt-get clean -y

COPY src/requirements.txt .
RUN pip install -r requirements.txt

#seteo esta variable porque estoy trayendo el gdal de manera externa y no compilandolo con gcc
ENV GDAL_DATA=/usr/local/lib/python3.9/site-packages/fiona/gdal_data