FROM python:3.9.3-slim-buster

#librerías necesarias
#RUN pip install rasterio geopandas pycrs watchdog inotify_simple
RUN apt-get update \
    && apt-get upgrade \
    && apt-get install -y libgomp1 \
    && apt-get clean

COPY src/requirements.txt .
RUN pip install -r requirements.txt

#seteo esta variable porque estoy trayendo el gdal de manera externa y no compilandolo con gcc
ENV GDAL_DATA=/usr/local/lib/python3.9/site-packages/fiona/gdal_data